function model = make_model(Fext,opt)
  arguments
    Fext
    opt.threshold (1,1)  {mustBeNumeric} =  0.002;
    opt.fc (1,1) {mustBeNumeric} = 10;
    opt.deltaP (1,1) {mustBeNumeric} = 0.045;
    opt.trefract (1,1) {mustBeNumeric}  = 0.3;
    opt.Pmax (1,1) {mustBeNumeric}  = inf;
    opt.Pmin (1,1) {mustBeNumeric}  = 0.1;
    opt.Pt (1,1) {mustBeNumeric}  = 1;
    opt.Px (1,1) {mustBeNumeric}  = 0;
    %opt.pl1 (1,1) {mustBeNumeric} = 0.02/120;
    opt.pl1 (1,1) {mustBeNumeric} = 1;
    opt.pl2 (1,1) {mustBeNumeric} = 0;
    opt.pk1 (1,1) {mustBeNumeric} = 1;
    opt.pk2 (1,1) {mustBeNumeric} = -1;
    opt.m (1,1) {mustBeNumeric} = 1;
    opt.b (1,1) {mustBeNumeric} = 1;
    opt.L (1,1) {mustBeNumeric} = 1;
    %opt.r0 (1,1) {mustBeNumeric} = 0.01;
    opt.r0 (1,1) {mustBeNumeric} = 1;
    opt.nu (1,1) {mustBeNumeric} = 0.1;
    opt.C (1,1) {mustBeNumeric} = 1;
  end

fprintf('Creating Hybid Model\n\n');

% -- PAM model Parameters
tauT = 0.1; % tank
tauL = Inf; % leakage
tauE = 0.2; % exhaust
Pt = opt.Pt;
Px = opt.Px;
Pmin = opt.Pmin;
Pmax = opt.Pmax;

% -- Mechanics Parameters
L = opt.L;
m = opt.m;
b = opt.b;

% -- Volume-parameters
r0 = opt.r0;
nu = opt.nu;
C = opt.C;

% -- Reflex parameters
fc = opt.fc;
threshold = opt.threshold;
deltaP = opt.deltaP;
trefract = opt.trefract;

% -- Pressure Valve dyanmics
f_nom =@(P) (1/tauL)*(Px - P);
f_inf =@(P) (1/tauT)*(Pt - P);
f_def =@(P) (1/tauE)*(Px - P);

% -- Volume/Pressure dynamics
rf =@(x) r0 + nu*x;
re =@(x) r0 - nu*x;
%rf =@(x) r0 + nu*(r0/L).*x;
%re =@(x) r0 - nu*(r0/L).*x;

%Vf =@(x) pi*rf(x).^2.*(L+x);
%dVf =@(x,dx) pi.*dx.*(2.*rf(x).*(L+x)+rf(x).^2);
%Ve =@(x) pi*re(x).^2.*(L-x);
%dVe =@(x,dx) pi.*dx.*(2.*re(x).*(L-x)-re(x).^2);
%%
Vf =@(x) pi*rf(x).^2.*(L+x);
dVf =@(x,dx) pi*dx.*(2*rf(x)*nu*(r0/L).*(L+x)+rf(x).^2);
Ve =@(x) pi*re(x).^2.*(L-x);
dVe =@(x,dx) -pi*dx.*(2*re(x)*nu*(r0/L).*(L-x)+re(x).^2);

% -- Pressure-stiffness and Pressure-length relationship
%k =@(P) (1.*P + 1);
pk1 = opt.pk1;
pk2 = opt.pk2;
pl1 = opt.pl1;
pl2 = opt.pl2;
k =@(P) (pk1.*P + pk2);
%k =@(P) pk1*exp(pk2*P);
l =@(P) -pl1.*P + pl2;
%l =@(P) -pl1.*exp(pl2*P);


%figure;
%  pp = Px:0.1:Pt;
%  plot(pp,k(pp));
%
%return

% -- displacement and forces
xi =@(P) (L - l(P));
Ff =@(Pf,x) k(Pf).*(xi(Pf)-x);
Fe =@(Pe,x) -k(Pe).*(xi(Pe)+x);
Fd =@(dx) -b.*dx;


% -- Equilbrium point
xeq =@(P1,P2) (1./(k(P1) + k(P2))).*(k(P1).*(L - l(P1)) - k(P2).*(L - l(P2)));

% -- activation signal dynamics (HP filter) -- (see note on diff. eq.
% implementation)
fe =@(Pf,Pf0,Pe,Pe0) (Pf0-Pf)-(Pe0-Pe);
ft =@(a,e) (2*pi*fc)*(e-a);
da =@(a,e) (2*pi*fc)*(e-a);

% -- Equation of motion for mass
dz =@(t,z,Pf,Pe,Fext) ...
      [z(2); ...
      (Ff(Pf,z(1)) + Fe(Pe,z(1)) + Fext + Fd(z(2)))/m];

% Helpers
fvec =@(varargin) varargin{:};
modes = struct([]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Hybrid Dyanmical Systems Model
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   [1 2  3  4  5   6   7     8   9    10  11 ]
% State Vector: x = [z dz Pf Pe a | Pfd Ped | Pf0 Pe0 |tf0 te0]

% For double event -- use third event for tie

%------------------------------------------------------------------------------
% Level 1
%------------------------------------------------------------------------------

% ---
% MODE - P (Perception)
%
% Edges: ID (Inflate-Deflate), DI (Deflate-Inflate)
mi = 1;
modes(mi).domain = 'P';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        da(x(5),fe(x(3),x(8),x(4),x(9))); ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec(...
                      [ft(x(5),fe(x(3),x(8),x(4),x(9))) + threshold; ...
                       ft(x(5),fe(x(3),x(8),x(4),x(9))) - threshold], ...
                      [1; 1], ...
                      [-1; 1]);
modes(mi).edges = {'DI','ID'};
modes(mi).jumpmaps = {  @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                            max(Pmin,x(6)-deltaP); min(Pmax,x(7)+deltaP); ...
                            x(8); x(9); x(10); x(11)], ...
                        @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                            min(Pmax,x(6)+deltaP); max(Pmin,x(7)-deltaP);
                            x(8); x(9); x(10); x(11)]};


%------------------------------------------------------------------------------
% Level 2
%------------------------------------------------------------------------------

% ---
% MODE - ID (Inflate-Deflate)
%
% Edges: RD (Inflate-Refract), IR (Refract-Deflate)
mi = mi+1;
modes(mi).domain = 'ID';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_inf(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_def(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(3) - x(6); ...
                       x(4) - x(7)], ...
                      [1; 1], ...
                      [1; -1]);
modes(mi).edges = {'RD','IR','RR'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; t]};

% ---
% MODE - DI (Deflate-Inflate)
%
% Edges: RI (Refract-Inflate), DR (Deflate-Refract)
mi = mi+1;
modes(mi).domain = 'DI';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_def(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_inf(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(3) - x(6); ...
                       x(4) - x(7)], ...
                      [1; 1], ...
                      [-1; 1]);
modes(mi).edges = {'RI','DR','RR'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; t]};

%------------------------------------------------------------------------------
% Level 3
%------------------------------------------------------------------------------

% ---
% MODE - RD (Refract-Deflate)
%
% Edges: 0D (wait-deflate) RR (refract-refract)
mi = mi+1;
modes(mi).domain = 'RD';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_def(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [(t-x(10))-trefract; ...
                       x(4) - x(7)], ...
                      [1; 1], ...
                      [1; -1]);
modes(mi).edges = {'0D','RR','0R'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t]};

% ---
% MODE - IR (inflate-refract)
%
% Edges: RR (refract-refract) I0 (inflate-wait)
mi = mi+1;
modes(mi).domain = 'IR';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_inf(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(3) - x(6); ...
                       (t-x(11))-trefract], ...
                      [1; 1], ...
                      [1; 1]);
modes(mi).edges = {'RR','I0','R0'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)]};

% ---
% MODE - RI (refract-inflate)
%
% Edges: 0I (wait-inflate) RR (refract-refract)
mi = mi+1;
modes(mi).domain = 'RI';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_inf(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [(t-x(10))-trefract; ...
                       x(4)-x(7)], ...
                      [1; 1], ...
                      [1; 1]);
modes(mi).edges = {'0I','RR','0R'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t]};

% ---
% MODE - DR (deflate-refract)
%
% Edges: RR (refract-refract) D0 (deflate-wait)
mi = mi+1;
modes(mi).domain = 'DR';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_def(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(3)-x(6); ...
                       (t-x(11))-trefract], ...
                      [1; 1], ...
                      [-1; 1]);
modes(mi).edges = {'RR','D0','R0'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)]};

%------------------------------------------------------------------------------
% Level 4
%------------------------------------------------------------------------------

% ---
% MODE - 0D (wait-deflate)
%
% Edges:  0R (wait-refract)
mi = mi+1;
modes(mi).domain = '0D';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_def(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(4)-x(7)], ...
                      [1], ...
                      [-1]);
modes(mi).edges = {'0R'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t]};

% ---
% MODE - D0 (deflate-wait)
%
% Edges: R0 (refract-wait)
mi = mi+1;
modes(mi).domain = 'D0';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_def(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(3)-x(6)], ...
                      [1], ...
                      [-1]);
modes(mi).edges = {'R0'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)]};

% ---
% MODE - I0 (inflate-wait)
%
% Edges: R0 (refract-wait)
mi = mi+1;
modes(mi).domain = 'I0';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_inf(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(3)-x(6)], ...
                      [1], ...
                      [1]);
modes(mi).edges = {'R0'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); t; x(11)]};

% ---
% MODE - 0I (wait-refract)
%
% Edges: 0R (wait-refract)
mi = mi+1;
modes(mi).domain = '0I';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_inf(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [x(4)-x(7)], ...
                      [1], ...
                      [1]);
modes(mi).edges = {'R0'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); t]};

% ---
% MODE - RR (refract-refract)
%
% Edges: 0R (wait-refract) R0 (refract-wait) | (tie-case) P (perception)
mi = mi+1;
modes(mi).domain = 'RR';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [(t-x(10))-trefract; ...
                       (t-x(11))-trefract], ...
                      [1; 1], ...
                      [1; 1]);
modes(mi).edges = {'0R','R0','P'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(8); x(9); x(10); x(11)], ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(3); x(4); x(10); x(11)]};

%------------------------------------------------------------------------------
% Level 5
%------------------------------------------------------------------------------

% ---
% MODE - 0R (wait-refract)
%
% Edges: P (perception)
mi = mi+1;
modes(mi).domain = '0R';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [(t-x(11))-trefract], ...
                      [1], ...
                      [1]);
modes(mi).edges = {'P'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(3); x(4); x(10); x(11)]};
% ---
% MODE - R0 (refract-wait)
%
% Edges: P (perception)
mi = mi+1;
modes(mi).domain = 'R0';
modes(mi).flow =  @(t,x,xp) xp - [dz(t,x(1:2),x(3),x(4),Fext(t,x(1:2))); ...
                        f_nom(x(3)) - C*dVf(x(1),x(2))/Vf(x(1))^2; ...
                        f_nom(x(4)) - C*dVe(x(1),x(2))/Ve(x(1))^2; ...
                        0; ...
                        0; 0; 0; 0; 0; 0];
modes(mi).guards = @(t,x,xp) fvec( ...
                      [(t-x(10))-trefract], ...
                      [1], ...
                      [1]);
modes(mi).edges = {'P'};
modes(mi).jumpmaps = { ...
                @(t,x) [x(1); x(2); x(3); x(4); 0; ...
                        x(6); x(7); x(3); x(4); x(10); x(11)]};


% Return model + any special functions you need
model.modes = modes;

% functions
model.xeq = xeq;
model.k = k;
model.l = l;
model.xi = xi;
model.Ff = Ff;
model.Fe = Fe;
model.da = da;
model.fe = fe;
model.ft = ft;
model.rf = rf;
model.re = re;
model.Vf = Vf;
model.Ve = Ve;
model.dVf = dVf;
model.dVe = dVe;

% parameters
model.threshold = threshold;
